### PR TITLE
Updated cmake for building against VMC standalone by default

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
1. as default try to build against VMC standalone
2. if not found, fallback to ROOT and try to build against its builtin
   VMC

### CODE REVIEW

**Comment by ihrivnac** [comment]
@benedikt-voelkel ,

There is no reason to repeat find_package(ROOT ...) if VMC standalone is not found, as the info whether ROOT is built with VMC is available after the first find_package in the ROOT_vmc_FOUND variable. Also the error message, if both founds failed, can be more explicit. Can you change the code as follows?

```
#-- VMC (required) ------------------------------------------------------------
find_package(VMC CONFIG)
set(VMC_DEPS VMCLibrary)
if(NOT VMC_FIND_QUIETLY)
  message(STATUS "Found VMC ${VMC_VERSION} in ${VMC_DIR}")
endif()

if(NOT VMC_FOUND)
  if(ROOT_vmc_FOUND)
    message(WARNING "Using VMC built with ROOT - Deprecated")
    set(VMC_DEPS ROOT::VMC)
    add_definitions(-DUSE_ROOT_VMC)
  else()
    message(FATAL_ERROR 
        "Could not find VMC package. "
        "VMC package is not provided with ROOT since v6.26/00. "
        "Please, install it from https://github.com/vmc-project/vmc. ")
  endif()
endif()

```

Then, a similar change is also needed in FindVMCPackages.cmake, which is used by the VMC examples. (Note this file is provided in both geant3 and geant4_vmc and should be identical.)

**Comment by benedikt-voelkel** [comment]
I added `FindVMC.cmake` to avoid code duplication and changed as requested @ihrivnac

**Comment by ihrivnac** [comment]
I prefer not to provide FindVMC as the VMC provides it Config file. The code is not that long to justify introducing this file, which enters in competition to the VMCConfig file. Can you, please, just replace the existing code in VMCPackages.cmake and remove FindVMC.cmake?

**Comment by benedikt-voelkel** [comment]
Hej @ihrivnac 
Thanks for the feedback! To be honest I found/find it a bit confusing to have this code duplication. But if that is the preferred way in VMC, I will change it. Not much work indeed.

**Comment by ihrivnac** [comment]
Thank you. Can you, please, use 2 spaces indention to be consistent with the existing cmake files?

**Comment by benedikt-voelkel** [comment]
Sorry for not paying attention to that earlier. It is done

**Comment by ihrivnac** [comment]
Please, note that the setting in FindVMCPackages.cmake under each condition (vmc standalone/vmc from ROOT) is different than Geant3RequiredPackages.cmake. Could you, please, fix the code, so that it defines the same variables as before but with just inverted find logic?

**Comment by benedikt-voelkel** [comment]
Hello @ihrivnac 
That was a bit of a mess from my side... Let me know if you have any other comments.

**Comment by ihrivnac** [comment]
There is still a fix needed; as we removed REQUIRED from find_package(VMC CONFIG), we need to add a test if VMC was found, otherwise we get a messy message (see the 2nd line) :

```
-- Could NOT find VMC (missing: VMC_DIR)
-- Found VMC  in VMC_DIR-NOTFOUND
CMake Warning at cmake/Geant3RequiredPackages.cmake:32 (message):
  Using VMC built with ROOT - Deprecated
```
The updated code (note also the internal comments a bit reduced):

```
#-- VMC (required) ------------------------------------------------------------
find_package(VMC CONFIG) 
# first try VMC standalone (default)
if(VMC_FOUND) 
  set(VMC_DEPS VMCLibrary)
  if(NOT VMC_FIND_QUIETLY)
    message(STATUS "Found VMC ${VMC_VERSION} in ${VMC_DIR}")
  endif()
else()
  # otherwise fallback to ROOT's internal if possible (deprecated)
  if(ROOT_vmc_FOUND)
    message(WARNING "Using VMC built with ROOT - Deprecated")
    set(VMC_DEPS ROOT::VMC)
    add_definitions(-DUSE_ROOT_VMC)
  else()
    message(FATAL_ERROR
            "Could not find VMC package. "
            "VMC package is not provided with ROOT since v6.26/00. "
            "Please, install it from https://github.com/vmc-project/vmc. ")
  endif()
endif()
```

And similarly, the test should be also added in the second file.

**Comment by benedikt-voelkel** [comment]
I added the `QUIET` option to the standalone `find_package` since otherwise CMake would generate the error/warning automatically. Any test after `find_package` would be too late to catch that warning.
Now I just added the message about which `VMC` version was used by default, taking out the `if (NOT VMC_FIND_QUIETLY)`

**Comment by benedikt-voelkel** [comment]
Dear @ihrivnac 
Is there anything else to be considered?

**Comment by ihrivnac** [comment]
@benedikt-voelkel ,
I wrote a reply yesterday and waited for finishing a test, and it looks like I did not click the button at the end and my comment was lost. Here it is again.

We do not worry about the warning on the first line in the log above, as this happen when using the deprecated option. But the info on the second line:
`-- Found VMC  in VMC_DIR-NOTFOUND
`
is wrong and it is fixed in the code above.

So there is no reason to add QUIET which can make difficult spotting the problems; and removing "`if(NOT VMC_FIND_QUIETLY)`" disables the possibility to suppress the info messages from the user side, so again there is no reason for removing it here. 

The code that I put in my previous comment is tested with both options (vmc standalone and vmc in Root) and works ok, so I just expected that you update your branch with it and update in an analogous way the second file.

**Comment by benedikt-voelkel** [comment]
@ihrivnac done

**Comment by ihrivnac** [comment]
@benedikt-voelkel , thank you. 
Can you create the PR with the same update in geant4_vmc, so that we can do the switch in both repositories at the same time?

**Comment by benedikt-voelkel** [comment]
@ihrivnac Sure. And also FLUKA_VMC?

**Comment by ihrivnac** [comment]
Yes. But as FLUKA_VMC is not in the vmc-project github, and not tested in the vmc examples test suite (in geant4_vmc), I think, it is not critical if the switch in fluka is done after accepting the PRs here.

**Pull request merged**
