### PR TITLE
Make ready for multiple engine usage

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
With this commit GEANT3 becomes capable of running together with other
engines sharing the simulation of one event. Depending on user
condistions, tracks might be transported by an engine based on geometry
constraints, particle type of phase space. When these conditions are not
met anymore, the VMC TMCManager interrupts the transport and transfers
the track to the engine responsible under the new conditions. This can
happen multiple times and is done automatically until all tracks have
been fully transported.

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Hello @ihrivnac 
how do we want to treat the additional white spaces which are all over the place
1) I can ignore these in my PR
2) you could also remove them in the master and I rebase afterwards
3) we take this PR as is

I guess you might want to test all current GEANT4_VMC examples with this PR before merging.

Just let me know how you want to proceed.

**Comment by ihrivnac** [comment]
I will update TGeant3 with removal of trailing whitespaces; when done, you will rebase your branch.
And yes, I will test both Geant3/Geant4 VMC updates together before merging.

**Comment by benedikt-voelkel** [comment]
Hello @ihrivnac 
The changes applied in the latest commit here are usable with https://github.com/vmc-project/vmc/pull/1. No change in GEANT4_VMC required

Will finally resolve the merge conflicts after lunch

**Comment by benedikt-voelkel** [comment]
Hej @ihrivnac 

I just opened another PR #9 since although I could change the branch to merge to but not the one to pull from. So to not confuse myself I didn't want to change my branches.
So I guess you can close this one.

**Pull request closed without merging**
