### PR TITLE
Update masses

### PR DESCRIPTION
**Pull request by chiarazampolli**
This commit is driven by the observation of a difference in the mass for some long-lived particles between the values in G3 and those in PDG 2020. 

The proposed values are taken from: http://pdg.lbl.gov/2020/listings/contents_listings.html, using the FIT values when both FIT and AVERAGE are available (the two values are always consistent within uncertainties).

See https://alice.its.cern.ch/jira/browse/ALIROOT-8463

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Pinging @fprino, @amorsch, @ihrivnac, @gconesab, @catalinristea

**Comment by ihrivnac** [comment]
@chiarazampolli ,
I compared the modified masses with the values in Geant4, see:

- http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/html/TrackingAndPhysics/AllResources/TrackingAndPhysics/particleList.src/mesons/index.html

- http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/html/TrackingAndPhysics/AllResources/TrackingAndPhysics/particleList.src/baryons/index.html

and they match exactly except for Kaon's, where G4 value is 4.976140e-01 while in your PR they are 0.497611.

**Comment by chiarazampolli** [comment]
Hello @ihrivnac , I took the values from PDG 2020, http://pdg.lbl.gov/2020/listings/rpp2020-list-K-zero.pdf, I would stick to that. I don't know where the G4 value comes from... 

Cheers,

Chiara

**Comment by ihrivnac** [comment]
Ok, thanks. Should we wait with merging for a feedback from someone from the people you pinged?

**Comment by chiarazampolli** [comment]
Hello, 

I am re-pinging them (@fprino , @amorsch , @gconesab , @catalinristea ). If there is no further comment by tomorrow afternoon, I would merge. @fprino had already a look some days ago when the PR was still not opened.

Chiara

**Comment by fprino** [comment]
Hi,
I confirm I had already checked the modification before the PR was open and it is fine with me.
Cheers, Francesco

**Comment by amorsch** [comment]
Also fine with me.
Cheers
Andreas

**Comment by gconesab** [comment]
No comment from my side, it looks good.

Gustavo

**Comment by ihrivnac** [comment]
Thank you all for checking; the PR is now merged. I will make a new tag later today. Do we need this development also in the branch based on ROOT 5?

**Comment by chiarazampolli** [comment]
Hello @ihrivnac , 

Thanks! Yes, please, also for ROOT5.

Cheers,

Chiara

**Pull request merged**
