### PR TITLE
Use explicit EQUIVALENCE to fix the issues on MacOSX Sonoma

### PR DESCRIPTION
**Pull request by pzhristov**
It seems the implicit alignment (EQUIVALENCE in terms of Fortran) of common blocks with the same name and different content is removed in the linker of MacOS Sonoma. Since /COMMON/GCBANK/ that was initially created in gcinit.F with a dummy array to allocate the memory, and then redefined in geant321/gcbank.inc, only the last was seen at execution time and we got overlapping ZEBRA banks.

### CODE REVIEW

**Comment by pzhristov** [comment]
Hi @ihrivnac, would you merge this PR and create a new tag?
Thanks, Peter

**Comment by ihrivnac** [comment]
Hi @pzhristov,

I am still getting break segmentation when testing your patch on macOS Sonoma 14.6.1, with XCode 15.4. Do you have the same versions ?

And if so, can you test the E01 example (provided in geant4_vmc):
```
cd geant4_vmc/examples/E01
root
root [0] .x load_g3.C 
root [1] .x run_g3.C 
```
Thank you.

**Comment by pzhristov** [comment]
Hi @ihrivnac, I run the two macros In E01 and got correctly the output. In addition I tested E02 and E02 getting the expected results and pictures. I am running Sonoma 14.6.1 on Mac mini M1. The Xcode version is 15.4 (15F31d).

**Comment by ihrivnac** [comment]
Thank you, @pzhristov , for testing. I checked that on my side, the VMC tests pass ok in the ALICE environment. I will merge and continue to investigate what is different when building standalone.

**Comment by fuhlig1** [comment]
@ihrivnac,

I encountered the same problem on my mac. When running the example E01 with version 4-2 of geant3 I get the following crash

```
=============================================================
 Geant3 Virtual Monte Carlo 
 Version 4.2 ( 9 February 2023 )
 WWW : https://vmc-project.github.io/
=============================================================


 MZSTOR.  ZEBRA table base TAB(0) in /MZCC/ at adr   109731415     68A5E57 HEX

 MZSTOR.  Initialize Store  0  in /GCBANK/
          with Store/Table at absolute adrs   109218653   109731415
                                        HEX     6828B5D     68A5E57
                                        HEX    FFF82B36           0
                              relative adrs     -513226           0
          with     1 Str. in     2 Links in   5300 Low words in 4999970 words.
          This store has a fence of   16 words.

```
 
When running the example with the fixed version 4-4 of geant3 running the example didn't crash

```
=============================================================
 Geant3 Virtual Monte Carlo 
 Version 4.4 ( 12 September 2024 )
 WWW : https://vmc-project.github.io/
=============================================================


 MZSTOR.  ZEBRA table base TAB(0) in /MZCC/ at adr   144279815     8998907 HEX

 MZSTOR.  Initialize Store  0  in /GCBANK/
          with Store/Table at absolute adrs   144388545   144279815
                                        HEX     89B31C1     8998907
                                        HEX       1A6EA           0
                              relative adrs      108266           0
          with     1 Str. in     2 Links in   5300 Low words in 4999970 words.
          This store has a fence of   16 words.

 MZLOGL.  Set Log Level 0 for store  0
1*****  GEANT Version  3.21/11 Released on 100298
0*****  Correction Cradle Version  0.1100

 MZDIV.   Initialize Division  Constant  in Store  0
          NW/NWMAX=   20004000000,  MODE/KIND=  1  2
          Division 20 initialized.

 MZLINK.  Initialize Link Area  /GCLINK/  for Store  0 NL/NS=    20    20

 MZLINK.  Initialize Link Area  /GCSLNK/  for Store  0 NL/NS=   100   100
Geant3 has been created.
Geometry will be defined via TGeo
```

So I thought the problem was solved. Unfortunately when running the example again today in the same session the execution crashed again

```
=============================================================
 Geant3 Virtual Monte Carlo 
 Version 4.4 ( 12 September 2024 )
 WWW : https://vmc-project.github.io/
=============================================================


 MZSTOR.  ZEBRA table base TAB(0) in /MZCC/ at adr   205101319     C399907 HEX

 MZSTOR.  Initialize Store  0  in /GCBANK/
          with Store/Table at absolute adrs   205210049   205101319
                                        HEX     C3B41C1     C399907
                                        HEX       1A6EA           0
                              relative adrs      108266           0
          with     1 Str. in     2 Links in   5300 Low words in 4999970 words.
          This store has a fence of   16 words.

```

I have the feeling that the remaining problem is due to the memory region where the process is located but this currently only a feeling and not confirmed in any way.

**Pull request merged**
