### PR TITLE
Gcalor

### PR DESCRIPTION
**Pull request by MohammadAlTurany**
Add and build Gcalor with Geant3

### CODE REVIEW

**Comment by ihrivnac** [comment]
Hi @MohammadAlTurany ,

The added code (gcalor.F) produces 128 warnings on my Mac; the warnings are of this kind:

```
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:3221:18:

    40 CALL CERROR('CALSGM1$')
                  1
Warning: Actual argument contains too few elements for dummy argument ‘carg’ (8/50) at (1) [-Wargument-mismatch]

/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:12853:60:

          CALL THRMSC2(D,LD,XTHRMS,ITHRMS,LTHRM,E,U,V,W,TEMP,FM,AWR,IIN,
                                                            1
Warning: Rank mismatch in argument ‘fm’ at (1) (scalar and rank-1) [-Wargument-mismatch]

Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:1845:11:

    30 DO 40 I =1,60
                                                                        2
    40 IPEC(I) =0
           1
Warning: Array reference at (1) out of bounds (60 > 13) in loop beginning at (2)

```
Do you get them on your side, too?
The standard VMC tests are not affected, what's normal, as they do not use this code.

So, unless the warnings are fixed, I suggest to make the compilation of gcalor optional and disabled by default. Will this be ok for you? If so, let me know if you need a help with this.

Also, it would be good to add in the PR description (which I then pass to the Geant3 history file) the source of the code which is being added.

Thank you,

**Comment by MohammadAlTurany** [comment]
Hi @ihrivnac 

> Do you get them on your side, too?

Yes, I will look into that!

> So, unless the warnings are fixed, I suggest to make the compilation of gcalor optional and disabled by default. Will this be ok for you? If so, let me know if you need a help with this.

Ok, the PR will be updated 

> Also, it would be good to add in the PR description (which I then pass to the Geant3 history file) the source of the code which is being added.

There is a full description of the gcalor packages in the [geant3/README_gcalor](https://github.com/vmc-project/geant3/blob/master/README_gcalor) which I added in 2006 to geant3  [see here](https://github.com/vmc-project/geant3/commit/0cbd0e98212dbab768a36537bd3ee66aaab549fd)

**Comment by ihrivnac** [comment]
@MohammadAlTurany ,

Thank you for looking at this further.
Indeed, I found the README_gcalor file after posting my comment, too. This file will need to be updated with this PR, as the recipe for building gcalor will become obsolete when the code is included in geant3.

**Comment by dennisklein** [comment]
> So, unless the warnings are fixed, I suggest to make the compilation of gcalor optional and disabled by default.

@MohammadAlTurany I added a commit which makes the gcalor module optional. If you are able to fix the warnings, just drop it.

**Comment by dennisklein** [comment]
> Indeed, I found the README_gcalor file after posting my comment, too. This file will need to be updated with this PR, as the recipe for building gcalor will become obsolete when the code is included in geant3.

Also updated the `README_gcalor` file.

**Comment by ihrivnac** [comment]
@dennisklein ,
Thank you for the update; in README_gcalor, the link provided at the end of file is not working.

**Comment by dennisklein** [comment]
> Thank you for the update; in README_gcalor, the link provided at the end of file is not working.

Thx, I replaced the link.

**Comment by fuhlig1** [comment]
Hi @ihrivnac ,

I have fixed the compiler warnings. Most of them are related to mismatches of array sizes when passing arrays to subroutines. @kresan tested the changes and confirmed that he gets identical results before and after the fix.

**Comment by ihrivnac** [comment]
@fuhlig1 , 
Thank you for the fixes. I am still getting the following warnings (on my Mac, with clang 11.0.3):

```
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:1845:11:

    30 DO 40 I =1,60
                                                                        2
    40 IPEC(I) =0
           1
Warning: Array reference at (1) out of bounds (60 > 13) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:1847:11:

       DO 50 I =1,2114
                                                                        2
    50 ESPS(I) = 0.D0
           1
Warning: Array reference at (1) out of bounds (2114 > 481) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:1849:11:

       DO 60 I = 4515,4849
                                                                        2
    60 ESPS(I) = 0.D0
           1
Warning: Array reference at (1) out of bounds (4515 > 481) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:1849:11:

       DO 60 I = 4515,4849
                                                                        2
    60 ESPS(I) = 0.D0
           1
Warning: Array reference at (1) out of bounds (4849 > 481) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:4602:14:

    40 DO 50 I=1,60
                                                                        2
          IPEC(I)=0
              1
Warning: Array reference at (1) out of bounds (60 > 13) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:4607:14:

       DO 60 I=1,2114
                                                                        2
          ESPS(I)=0.0
              1
Warning: Array reference at (1) out of bounds (2114 > 481) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:4610:14:

       DO 70 I= 4515,4849
                                                                        2
          ESPS(I)=0.D0
              1
Warning: Array reference at (1) out of bounds (4515 > 481) in loop beginning at (2)
/Users/ivana/work/projects/vmc/new_vmc/geant3/gcalor/gcalor.F:4610:14:

       DO 70 I= 4515,4849
                                                                        2
          ESPS(I)=0.D0
              1
Warning: Array reference at (1) out of bounds (4849 > 481) in loop beginning at (2)


```

**Comment by fuhlig1** [comment]
@ihrivnac,

which version of gfortran do you use, or which fortran compiler do you use? clang 11.0.3 only gives the information about the C/C++ Compiler. I am using gfortran 10.2.0.


For me the warnings disappeared when adding the compiler flag -Wno-aggressive-loop-optimizations which is part of the default build setting for gcalor.F.

The warnings appear because the same common block is used in different subroutines differently (Probably the allocated memory is used differently). Since I only adapted gaclor but did not develop it myself I am not sure about the intention of the author.

**Comment by ihrivnac** [comment]
@fuhlig1 ,
I have GNU Fortran (GCC) 8.2.0; so it explains why we see different results. 
As this is fixed with newer version of compiler, and its anyway an optional package, I think we can safely merge now.

**Comment by dennisklein** [comment]
@ihrivnac When do you expect a new release? I am asking because I am in the process of updating our geant3 package in FairSoft and if there will be a new release soon, I could pick up some of the things we need via the new upstream version.

**Comment by ihrivnac** [comment]
@dennisklein , we usually make a release when a new tag is requested by users (mostly ALICE). I will make a tag today.

**Comment by ihrivnac** [comment]
@dennisklein , the new tag (v3-7) is now available.

**Comment by dennisklein** [comment]
> @dennisklein , the new tag (v3-7) is now available.

Thank you!

**Pull request merged**
