### PR TITLE
Add support for ROOT compiled with C++14

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @ihrivnac, can we have this merged if appropriate? Can we also have a new tag too? We need it to compile ALICE software using C++14. Thanks!

**Comment by ihrivnac** [comment]
Hi Dario,
Your patch is now merged, but one more update was needed, otherwise compilation failed in case ROOT configuration was defined via root-config.  Could you test if the current master still work ok for you?
I will wait for your confirmation before putting the new tag.

**Comment by dberzano** [comment]
@ihrivnac I'll do that ASAP - sorry for keeping you waiting!

**Comment by dberzano** [comment]
I confirm it works with:

* our legacy ROOT 5 installations,
* our ROOT 6 C++11 installations,
* our ROOT 6 C++14 installations.

Green lights for tagging on our side!

**Comment by ihrivnac** [comment]
Thank you, the tag is now available from github. There was one more fix needed (for ROOT 5.x found via system), but I believe this should not affect your tests.

**Pull request merged**
